export const CAR_BYTYPE_REQUEST = 'CAR_BYTYPE_REQUEST'
export const CAR_BYTYPE_SUCCESS = 'CAR_BYTYPE_SUCCESS'
export const CAR_BYTYPE_FAIL = 'CAR_BYTYPE_FAIL'

export const CAR_DETAIL_REQUEST = 'CAR_DETAIL_REQUEST'
export const CAR_DETAIL_SUCCESS = 'CAR_DETAIL_SUCCESS'
export const CAR_DETAIL_FAIL = 'CAR_DETAIL_FAIL'

export const CREATE_CAR_REQUEST = 'CREATE_CAR_REQUEST'
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS'
export const CREATE_CAR_FAIL = 'CREATE_CAR_FAIL'

export const EDIT_CAR_REQUEST = 'EDIT_CAR_REQUEST'
export const EDIT_CAR_SUCCESS = 'EDIT_CAR_SUCCESS'
export const EDIT_CAR_FAIL = 'EDIT_CAR_FAIL'