export const CREATE_IMAGE_REQUEST = 'CREATE_IMAGE_REQUEST'
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS'
export const CREATE_IMAGE_FAIL = 'CREATE_IMAGE_FAIL'

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST'
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL'