export const CART_LIST_REQUEST = 'CART_LIST_REQUEST'
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS'
export const CART_LIST_FAIL = 'CART_LIST_FAIL'

export const CART_SUMMARY_REQUEST = 'CART_SUMMARY_REQUEST'
export const CART_SUMMARY_SUCCESS = 'CART_SUMMARY_SUCCESS'
export const CART_SUMMARY_FAIL = 'CART_SUMMARY_FAIL'

export const CART_CHECKOUT_REQUEST = 'CART_CHECKOUT_REQUEST'
export const CART_CHECKOUT_SUCCESS = 'CART_CHECKOUT_SUCCESS'
export const CART_CHECKOUT_FAIL = 'CART_CHECKOUT_FAIL'