export const ADD_LITE_REQUEST = 'ADD_LITE_REQUEST'
export const ADD_LITE_SUCCESS = 'ADD_LITE_SUCCESS'
export const ADD_LITE_FAIL = 'ADD_LITE_FAIL'

export const EDIT_LITE_REQUEST = 'EDIT_LITE_REQUEST'

export const DELETE_LITE_REQUEST = 'DELETE_LITE_REQUEST'