export const ALL_ORDER_REQUEST = 'ALL_ORDER_REQUEST'
export const ALL_ORDER_SUCCES = 'ALL_ORDER_SUCCESS'
export const ALL_ORDER_FAIL = 'ALL_ORDER_FAIL'

export const ONE_ORDER_REQUEST = 'ALL_ORDER_REQUEST'
export const ONE_ORDER_SUCCES = 'ALL_ORDER_SUCCESS'
export const ONE_ORDER_FAIL = 'ALL_ORDER_FAIL'

export const ORDER_LITE_REQUEST = 'ORDER_LITE_REQUEST'
export const ORDER_LITE_SUCCES = 'ORDER_LITE_SUCCESS'
export const ORDER_LITE_FAIL = 'ORDER_LITE_FAIL'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCES = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'

export const GLOBAL_ORDER_REQUEST = 'GLOBAL_ORDER_REQUEST'
export const GLOBAL_ORDER_SUCCES = 'GLOBAL_ORDER_SUCCESS'
export const GLOBAL_ORDER_FAIL = 'GLOBAL_ORDER_FAIL'